### ISSUE TITLE
Demo not working: Usage examples missing.

### ISSUE THREAD

**Issue by pm2002** [hatemalimam/animatejsf#1]
The demo domain [animatejsf.org](http://animatejsf.org) is currently not working anymore. Could you please offer some usage examples that fully show how to integrate AnimateJSF. I wasn't yet able to get it running and documentation is, let's say, a little sparse in this regard.

**Comment by hatemalimam** [comment]
You may refer to http://jsf.hatemalimam.com/animatejsf/

**Comment by pm2002** [comment]
Could you please provide the sources of your showcase as github project? I already set up a example project using your documented maven dependency, namespace and usage tag: but it's not working properly. So no idea, what's wrong. Working example code would be helpful!

**Comment by hatemalimam** [comment]
It's already in my repos, check it out https://github.com/hatemalimam/animatejsfshowcase

More precisely [here](https://github.com/hatemalimam/animatejsfshowcase/blob/master/src/main/webapp/index.xhtml#L19)

**Comment by pm2002** [comment]
Thanks, I somehow must have missed this. I still have the integration issues in an existing project, but this will help me to figure out where this problem is coming from. Thanks for your reply.
